create table if not exists public.datameta (
	datameta_id bigint generated by default as identity,
	data_id bigint default 0,
	meta_key character varying default null,
	meta_value text default null,
    constraint datameta_pkey primary key (datameta_id)
)tablespace pg_default;
