create table if not exists public.datameta (
	datameta_id bigint generated by default as identity,
	data_id bigint default 0,
	meta_key character varying default "",
	meta_value text default "",
    constraint data_pkey primary key (id)
)tablespace pg_default;
