create table
  public.data (
	id bigint generated by default as identity,
	data_title text "",
	data_content text "",
	data_content_integer bigint 0,
	data_type character varying "",
	data_name character varying "",
	data_status character varying "",
	data_parent character varying "",
	data_author bigint 0,
	data_date character varying "",
	data_update character varying "",
    constraint data_pkey primary key (id)
)tablespace pg_default;
